---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fedora-atomic-sway-bluebuild
# description will be included in the image's metadata
description: My personal Fedora Sericea (Sway Atomic) image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/sericea
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    # repos:
    #   copr:
    #     - atim/starship
    install:
      packages:
        - gh
        - tealdeer
        - chezmoi
        # - micro
        # - starship
    remove:
      packages:
        # removing firefox RPM in favor of the flatpak (faster security updates)
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    # Two configurations: one for system-wide apps, one to enable user-scope Flathub
    configurations:
      - notify: true
        # system = /var/lib/flatpak, available for all users, requires root to modify
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      # user = ~/.local/share/flatpak, per-user apps, user can install without root
      - scope: user
        # no install list here = just enables Flathub repo for user-installed apps

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
